### ISSUE TITLE
vhs combine does not convert node names

### ISSUE THREAD

**Issue by TingTingin** [Kosinkadink/ComfyUI-VideoHelperSuite#103]
When using naming in comfyui you can add the date month and year to the save filename by using patterns like 

`%date:dd-MM-yyyy%`

This works with vhs currently however another feature is the ability to use the names from nodes in this way 

`%Load Checkpoint.ckpt_name%`

This gets the checkpoint name from the Load Checkpoint node when i use %date:dd-MM-yyyy%/%Load Checkpoint.ckpt_name%/imag with the save image node it gives me the check point name like

`27-12-2023\juggernautXL_v7Rundiffusion.safetensors`

But with vhs i get

`27-12-2023\%Load Checkpoint.ckpt_name%`

Its not converting the name appropriately

**Comment by AustinMroz** [comment]
A fix for this was just added yesterday. Have you updated recently?

**Comment by Kosinkadink** [comment]
Can you try to refresh your page with Ctrl+F5 after the update to make sure your browser is not using cached JavaScript?
