### ISSUE TITLE
Workflows unusable since last update 

### ISSUE THREAD

**Issue by Djanghost** [Kosinkadink/ComfyUI-VideoHelperSuite#107]
Since the last update, I've been unable to open some of my workflows in comfyUI. Here's the error message:
![Capture d'écran 2023-12-28 173341](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/129005283/9e8df9ea-44ec-4bb9-a3e5-98d7866e082a)

**Comment by wangzan1990** [comment]
same issue

**Comment by wangzan1990** [comment]
conflict with FizzNodes' BatchPromptSchedule?

**Comment by AustinMroz** [comment]
I made a minor mistake when updating the path widget conversion code and forgot to account for nodes with no widgets, like Get Image Count. It should be fixed now.
