### ISSUE TITLE
In Load Video node, skip_first_frames does not work as intended (in ffmpeg path) and returns skip_first_frames+frame_load_cap frames

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#11]
<img width="290" alt="image" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/7365912/5559bfaa-14b8-4909-b96d-12b672ea5b01">

Had this reported to me in discord, currently not home so I can't take a look myself

**Comment by AustinMroz** [comment]
The issue appears to occur only in videos that have audio and, further, passing the no audio flag ('-an') is not sufficient to fix things in a single pass. I'll do some more digging tomorrow, but it seems my understanding of the 'select' filter was misguided. I had hoped it would improve performance by skipping the encoding of frames, but it's providing a noticeable undesirable slowdown on longer videos

**Comment by Kosinkadink** [comment]
If need be, we can temporarily make Load Video use the opencv fallback all the time while the ffmpeg impl is being resolved
