### ISSUE TITLE
VHS_LoadImagesFromPath

### ISSUE THREAD

**Issue by KazexG** [Kosinkadink/ComfyUI-VideoHelperSuite#116]
Hey, After last update i keep getting this error from the loadimages from path node. 

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/148649064/144c4af1-c755-4d9a-a668-0288932fac5d)

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/148649064/ec83a579-a181-42ec-b0d5-1c3463a42ee6)

The other node LoadImages works fine

Steps taken: 

- Reinstalled video helper suite
- updated comfyui + all packs ( including video helper suite)

Thanks in advance

**Comment by AustinMroz** [comment]
This appears to be a duplicate of #113, which had a fix pushed within a matter of minutes of you opening the issue.
