### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable, when using VHS in python code

### ISSUE THREAD

**Issue by HanJu-Chen** [Kosinkadink/ComfyUI-VideoHelperSuite#118]
When I run the workflow after switching to python code, I get this error.
![微信截图_20240104135953](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/96210358/a3da9f03-5501-48bf-8554-9e9059f774e1)
In comfyui, my workflow is running successfully. But when converted to python code, the nonetype error occurs when saving the video using VHS.
![Snipaste_2024-01-04_14-02-38](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/96210358/71cdc312-73b3-4509-bbd1-d1d23bf3b4af)
I'm not quite sure why the error occurs when running in code, but not in comfyui. All my nodes load successfully.
![Snipaste_2024-01-04_14-01-21](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/96210358/d4407ba6-afa3-4677-84d3-6e69cf9f1892)

**Comment by HanJu-Chen** [comment]
[workflow_api_save_vedio.py.txt.txt](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/files/13826834/workflow_api_save_vedio.py.txt.txt)
[workflow_api_save_vedio.json](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/files/13826835/workflow_api_save_vedio.json)
Here's my workflow and python code.
It works when I don't use VHS in code to save the video and use save image to save it.

**Comment by 26medias** [comment]
That issue is most likely coming from using python 3.8. Solved by upgrading python.
