### ISSUE TITLE
[BUG] Load Video Path node throw error when custom_width and custom_height are piped in.

### ISSUE THREAD

**Issue by RangerFrank** [Kosinkadink/ComfyUI-VideoHelperSuite#119]
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/14126780/b3584462-3aac-4f1c-8c0a-048c08a34af7)

**Comment by AustinMroz** [comment]
Currently, the custom_width and custom_height widgets exist only in the javascript code and are applied to force_size upon serialization. I'll start on a fix to always pass custom_width and custom_height and instead do the formatting in the python code.
