### ISSUE TITLE
The video generated by the node of Video Combine is shaking, chaotic, and lacks color

### ISSUE THREAD

**Issue by jinnaluo0** [Kosinkadink/ComfyUI-VideoHelperSuite#126]
It is normal when setting parameters：format=image/gif.
It is abnormal when setting parameters：format=video/h265-mp4.
This is the workflow file( as an example):
[video_test.json](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/files/13926048/video_test.json)

**Comment by AustinMroz** [comment]
Thanks for bringing this up. With a couple additional tweaks, it transitions nicely into full transparency support.
![transparency](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/a26a8294-ea7a-4874-bf23-5937a7703949)
