### ISSUE TITLE
Only save one file when combining video and audio

### ISSUE THREAD

**Issue by SeanBannister** [Kosinkadink/ComfyUI-VideoHelperSuite#130]
I've noticed when using the Video Combine node with an audio input it saves two copies of the video file, one with the audio and one without. Could I suggest that this should only save the video file with the audio.

If a user wants a none audio version of their video they could just use two video combine nodes one with audio and one without.

Alternatively, any suggestions on how I could automatically delete the none audio version?

**Comment by AustinMroz** [comment]
To the extent of my knowledge and testing, having a temporary file without audio is required. There can be only one input pipe to ffmpeg of either video auto data or image data. I put a good bit of time experimenting with sending both sequentially, but could never find a workaround for the audio being interpreted as pixel data. 

As for potential workarounds, it should be feasible to add a new node that would take the `Filenames` output from the node and provide a number of cleanup options. I'll look into this tomorrow.
