### ISSUE TITLE
background removed gif overlapped

### ISSUE THREAD

**Issue by hongminpark** [Kosinkadink/ComfyUI-VideoHelperSuite#141]
Hi guys! Thanks for sharing useful custome node :) 
I have question. I am using VHS for animateDiff with background removed images, but I am getting result like this.
Frames look stacked to one another. 
Anyone know how to fix this ? 

<img width="365" alt="image" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/21957275/9f2ca412-cb5b-43fd-bbe4-d8b372144d6d">

**Comment by AustinMroz** [comment]
Thanks for catching this. I've pushed a fix for the issue.
