### ISSUE TITLE
select_every_nth > 1 results in trimmed audio

### ISSUE THREAD

**Issue by yuvraj108c** [Kosinkadink/ComfyUI-VideoHelperSuite#146]
When setting `select_every_nth` greater than 1, the output audio gets trimmed by that amount.

e.g If I have a video of 24 fps, I set `select_every_nth` to 2 and `frame_load_cap` to 24, the output audio duration gets trimmed by 2

**Comment by AustinMroz** [comment]
Thank you. This has been fixed.
