### ISSUE TITLE
How to select MP4 format in Video Combine's format input item?

### ISSUE THREAD

**Issue by shixinsama** [Kosinkadink/ComfyUI-VideoHelperSuite#147]
Video Combine format 
I can only choose GIF and Webm formats. There is no way to choose the H265 MP4 format output. Where can I add this option?

**Comment by AustinMroz** [comment]
The options for video outputs are unavailable when ffmpeg can not be found. The recommended fix is to either
- Install imageio-ffmpeg (see #77) or
- Manually download ffmpeg and add it to the system path.

**Comment by shixinsama** [comment]
Yes, I have already installed ffmpeg. But I forgot to restart ComfYUI, so I can't find it. This is my fault. Thank you for your answer.
