### ISSUE TITLE
VHS_FORCE_FFMPEG_PATH env var throws error

### ISSUE THREAD

**Issue by eighteyes** [Kosinkadink/ComfyUI-VideoHelperSuite#150]
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/blame/7cdb6b474fead62b41e7f7ea53a1910c88e5cbaf/videohelpersuite/utils.py#L34

Should likely be `os.environ`

**Comment by AustinMroz** [comment]
Thanks for noticing this, I'm near certain you are correct. 

I'm currently out of town, but will make sure this fix is applied when I return tomorrow evening.

**Comment by Kosinkadink** [comment]
I can get that merged in later today - the fix is to call ```os.getenv``` or ```os.environ.get```.

**Comment by Kosinkadink** [comment]
Fix included in the PR I will now merge: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/pull/151
