### ISSUE TITLE
Right click to Open,Sync and Save Preview is missing after the latest update.

### ISSUE THREAD

**Issue by Siraj-HM** [Kosinkadink/ComfyUI-VideoHelperSuite#152]
Hi,

Right-click to save the video, sync, hide, etc, are  missing after the latest update.

https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/139066507/ba97042c-249a-4834-b33e-edb88db99b35

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/139066507/547f438c-aa56-4ebd-ad08-86ea0156ac95)

Attached is a screen recording for reference. Tested in Chrome browser - Version 121.0.6167.139 (Official Build) (arm64)

**Comment by czcz1024** [comment]
which version of rgthree will be work?
