### ISSUE TITLE
[Feature Request] Extended "Creation/taken Date" Exif Metadata  into saved Images and Videos

### ISSUE THREAD

**Issue by xSemi** [Kosinkadink/ComfyUI-VideoHelperSuite#155]
Most cloud image/video services, including Amazon Photos and Google Photos, do not rely on the file's creation date or filename to organize images in their libraries. Instead, they use Exif metadata, such as Date Taken for JPG files or CreationTime for PNG files, to sort the content.

I was wondering if it would be possible to add the additional creation/taken Exif Metadata Information for all the different filetypes that supported by VHS.

**Comment by AustinMroz** [comment]
After a good bit of digging:
- Adding timestamps to video files produced with ffmpeg is a trivial 1 line change and can be easily tied to `save_metadata`
- Setting exif data for webp is doable. Theres no `save_metadata` option when using the webp format, but always saving a creation timestamp should be fine here.
- gifs only have a general comment field and do not have a standardized way of setting a timestamp

Would this be sufficient?

**Comment by xSemi** [comment]
mp4 should be fine if the timestamp add everything.
If those changes include the meta for JPG and PNG workflow images too its fine for me,  those are the formats that i atleast mostly use.
That what i figured out is the Tag DateTaken and DateTimeOriginal is for most Supported images, as far DateTimeOriginal is mostly commend used including webp and PNG has "CreationDate".
