### ISSUE TITLE
Load Audio [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by alterfo** [Kosinkadink/ComfyUI-VideoHelperSuite#158]
Hello!

I'm trying to load any audio in LoadAudio custom node, but always have the same error:

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/2650331/27e800ed-42f5-4d55-a5bb-21024d270925)

I have tried to 'pip install ffmpeg' in embedded python, but it didn't help.

**Comment by AustinMroz** [comment]
The error message you provide is for the ComfyUI-AudioScheduler Load Audio node, not the VHS Load Audio node.

I've never actually used pydub (the library used by AudioScheduler), but it appears to require ffprobe (which comes bundled with ffmpeg) be seperately installed and added to the system path. Further, I don't believe it's possible to add  ffmpeg to the system path with pip.

While I did, coincidentially, write a quick plugin recently to allow interoperability of AudioScheduler and VHS [here](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/discussions/1#discussioncomment-8474842) which would allow you to forgo the usage of AudioScheduler's load audio node, it comes with minimal guardrails and may not be much help.

**Comment by alterfo** [comment]
Just FYI,  ffmpeg removal from embedded python helped.
