### ISSUE TITLE
video combine does not composite audio into video

### ISSUE THREAD

**Issue by cyandddd** [Kosinkadink/ComfyUI-VideoHelperSuite#165]
as my title described, when i connect an audio input for videocombine node, it does not composite, it output a separate audio file instead.

here is my set up, i dont know what is wrong. I dont see anybody having this problem, probably i did something wrong but i cant figure out. please help!

<img width="623" alt="a7fb22dea4a68e9a4bf428ca967a712" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/109906409/4ed4ff1d-bdc6-4925-a2e8-0321e8b7111f">
<img width="865" alt="7cdae5e935066b83dfbd2ccb2d8bc4e" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/109906409/ca3c0628-67b8-4f08-ad47-8edadffafd07">
<img width="215" alt="e9d850010971b8858ec7209b699e621" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/109906409/d5064043-4e5a-4ef7-a472-2a249792419d">

**Comment by Kosinkadink** [comment]
That file should just be your video file with the audio attached - it makes the non-audio video before making the +audio version (both are video files - .MP4). Does that file not have your video as well as the audio?

**Comment by cyandddd** [comment]
thank you! my bad i didnt check the file with name "audio"

**Comment by brigan123** [comment]
the same problem as the questioner.
there was no such problem before but now
