### ISSUE TITLE
Video Combine Node Outputs png image along with video

### ISSUE THREAD

**Issue by ckao10301** [Kosinkadink/ComfyUI-VideoHelperSuite#169]
The video combine node is saving an extra png image along with the mp4 in the outputs folder. I do not want this image, because it's causing my serverless worker to send this extra data to my app via api. 

How can I stop this extra png image from being saved?

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/129625358/8bf8ed3c-ce55-4418-8763-d9a210e95fe7)

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/129625358/d63ca0b6-bb72-4437-abfb-a6e658186254)

**Comment by Tsubashi** [comment]
It looks like this png is the first frame of the video, and is written to preserve metadata. At the moment, there isn't any way to stop it from being written. See [this line](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/blob/47e56f3e42c3ab4fb33f1407c2c40b5391226621/videohelpersuite/nodes.py#L263) in nodes.py.
