### ISSUE TITLE
only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by MaxTran96** [Kosinkadink/ComfyUI-VideoHelperSuite#178]
hi, i'm getting this error

only integer tensors of a single element can be converted to an index

what does this mean? this is for the animate diff video to video workflow, the failed step is when saving video

**Comment by Kosinkadink** [comment]
Hey, can you post the full error stack from the console?

**Comment by MaxTran96** [comment]
ah it was a typo on my part, i fixed it
