### ISSUE TITLE
Video codecs do not load in Video Combine Node

### ISSUE THREAD

**Issue by bildmeister** [Kosinkadink/ComfyUI-VideoHelperSuite#180]
Hello,
In the video combine node I have only 2 choices of format, and they are not the codecs I have in the video format folder.
I am on Mac M1 in ComfyUI.
I can't find a clue as why the video formats do not present themselves in the node in the UI.

Any ideas would be very welcome!

![Screenshot 2024-03-27 at 01 12 46](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/31847955/084e1958-63a2-49c9-bb61-2a36bbf918c5)
<img width="354" alt="Screenshot 2024-03-27 at 01 06 34" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/31847955/cf929ce9-cff3-40e8-a5ee-f0a76cb1b748">

**Comment by AustinMroz** [comment]
This occurs when ffmpeg, which is required for most formats, can not be found. Either
- Install imageio-ffmpeg to the virtual environment used by ComfyUI or
- Install ffmpeg and add it to the system path

**Comment by bildmeister** [comment]
Thank you very much! Took a little study but it's working now!
