### ISSUE TITLE
 "Custom validation failed for node: video - Invalid file path:"

### ISSUE THREAD

**Issue by bkmikaelo7** [Kosinkadink/ComfyUI-VideoHelperSuite#196]
Hi, why am I getting this error?! It won't accept any directory. I'm on Mac. It has worked before.

Is there any other method for loading videos in to Comfy, from whatever directory in my machine. This method is so cumbersome and it's always a horrible hassle to get anything into comfy like this. This needs to be changed please.
Thanks and apologies.

**Comment by itsklimov** [comment]
+1

some logs

`comfyui     | invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
comfyui     | got prompt
comfyui     | Failed to validate prompt for output 161:
comfyui     | * VHS_LoadVideoPath 107:
comfyui     |   - Custom validation failed for node: video - Invalid file path: /Users/its/Movies/Untitled.mp4`

**Comment by AustinMroz** [comment]
Thanks for the additional logs.

Unfortunately, I don't have any good guess for why things aren't working here. It doesn't appear that there's been any sort of invalid parsing of the path, but the call to `os.path.isfile` still claims the file doesn't exist.

When you start typing in the path field, it provides suggestions. If you start typing in the path one folder at a time (`/` -> `/Users/` -> `/Users/its/`) does it at any point stop providing suggestions, or does it actually suggest the file?

**Comment by nothingness6** [comment]
I faced the same error. Did you figure it out?

**Comment by Kosinkadink** [comment]
We are consolidating this issue into the more recent issue: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/224

In that thread, I outline some info that would be useful to provide/try to try to narrow down why this happens for some people.
