### ISSUE TITLE
how to convert the filenames output of the video combine to string ?

### ISSUE THREAD

**Issue by proteus2000** [Kosinkadink/ComfyUI-VideoHelperSuite#202]
Hi

this is not really an issue. more like a question/ request.

i would like to get the output of the video combine node called filenames as a string. it seems it is a "tuple". do you have an idea how to convert the png and the mp4 filenames to a strings with existing nodes.  Or would it be possible to add extra string outputs containing the filenames to the node? would be helpful to directly open files from disk by copy/paste in explorer. and useful to use text in a more complex  workflow.
Thank you,
Boris

**Comment by proteus2000** [comment]
Screenshot

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/140195470/2c1b220d-99be-4e7b-99ad-6e0e91b56fd3)

**Comment by proteus2000** [comment]
wow thanks alot. will try that out

**Comment by moon47usaco** [comment]
This works great, thank you @AustinMroz 
@Kosinkadink  Can you add an official node that does this... =]
