### ISSUE TITLE
yup

### ISSUE THREAD

**Issue by White-Devil198** [Kosinkadink/ComfyUI-VideoHelperSuite#215]
yup

_Originally posted by @Ai-Haris in https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/discussions/214#discussioncomment-9526361_

**Comment by White-Devil198** [comment]
hbhhn

**Comment by Ai-Haris** [comment]
kjh

**Comment by Kosinkadink** [comment]
I don't know what's going on here, but this is spamming my email. Please stop lol

**Comment by Ai-Haris** [comment]
ok but i want badge
