### ISSUE TITLE
I Updated comfyui and all custom node and now I get this.

### ISSUE THREAD

**Issue by Cedri4** [Kosinkadink/ComfyUI-VideoHelperSuite#222]
I Updated comfyui and all custom node and now I get this.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/2d28561c-0db7-48d3-9690-05f7d10fab85)
In my workflow everything should work the path is correct, I've checked it in file explorer but the interesting part is that when I remove all the widtget and convert them as input it works.

The load video (path) and video combine nodes don't work.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/dad5d774-5ecb-421b-9328-541c78bf819c)
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/48704d5d-6f8c-4e33-a063-c3896a24ddb3)

**Comment by Cedri4** [comment]
Ah ah after a little recreation I got this error.
From what I understand for some reason it transforms it into a float
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/fad6a750-2959-47fb-8e9a-b262e390eb4d)
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/3f911901-373f-4115-ac01-0b0a9f295e8d)

**Comment by AustinMroz** [comment]
There's certainly some spookyness going on here. I don't have a proper reproduction, but I'll share what leads I have. The exact wording of `Invalid file path:` is produceed from an area with strict safety checks for None.  There was a very similar issue (#114) which was eventually traced to the node recieving the string "None" as input. 

From my recollection and quick testing, getting multiple lines of "Custom Validation failed for node" was fixed in ComfyUI last December.  I realize you said you just updated, but could you double check the version of ComfyUI you're on for my sanity?

**Comment by Cedri4** [comment]
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/33450d55-a373-42a1-9eb6-acbd2cba20ed)
Here's a image that shows that it's up to date, 13 hours after my initial message.

And as you can see on the second image the video input is  a path but I'll check if the output is the same.

**Comment by Cedri4** [comment]
Ok, this is a problem
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/b1a8bde1-a53d-4d48-8f71-426f024243f4)
And now the Load video with path works when I bypass the video combine and the filename thing. But when I debypass them I got a problem.
Since my explanation is not the best here's a video that shows the problem.


https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/f45d26fe-056a-4928-a822-1df28923dcf0

**Comment by Cedri4** [comment]
So after a second look on the terminal this custom node seems to cause a problem by converting the string to a float.
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/93396286/00d84251-1e77-451a-87f0-77ead0f321cc)
I disable it and now it works :)
I guess this custom node broke everything.
https://github.com/GMapeSplat/ComfyUI_ezXY
