### ISSUE TITLE
exif_transpose() got an unexpected keyword argument 'in_place'

### ISSUE THREAD

**Issue by ethanfel** [Kosinkadink/ComfyUI-VideoHelperSuite#226]
Hi, with the latests commits :

```
Error occurred when executing VHS_LoadImagesPath:

exif_transpose() got an unexpected keyword argument 'in_place'

  File "/media/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/comfyui/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_images_nodes.py", line 188, in load_images
    return load_images(directory, **kwargs)
  File "/media/comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_images_nodes.py", line 99, in load_images
    (width, height, has_alpha) = next(gen)
  File "/media/comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_images_nodes.py", line 52, in images_generator
    ImageOps.exif_transpose(i, in_place=True)
```

**Comment by ethanfel** [comment]
fixed by upgrading pillow

**Comment by AustinMroz** [comment]
Thanks for opening the issue. I hadn't noticed that the argument was a recent addition. Since the performance benefit is slim and no version requirements are placed on pillow (by us or comfy), I'll strongly consider removing the in_place arg anyways.

**Comment by ethanfel** [comment]
> Thanks for opening the issue. I hadn't noticed that the argument was a recent addition. Since the performance benefit is slim and no version requirements are placed on pillow (by us or comfy), I'll strongly consider removing the in_place arg anyways.

I have issues with other nodes since update pillow from the 0.9.5

**Comment by ethanfel** [comment]
I'm reopening this. Latest commits seems to breaks compatibility with other nodes.

With facetools : https://github.com/dchatel/comfyui_facetools/issues/7

this error appear only with VHS loader image batch from path. Other batch loader node work fine and VHS was working fine before

**Comment by AustinMroz** [comment]
Thank you very for the report of this. The recent update also experimentally changed loading to occur as float16 since it offered significant memory improvement and I couldn't find a place it would cause issues. Will take a moment to double check things and will roll that back as well.

**Comment by ethanfel** [comment]
glad to be able to help

**Comment by ethanfel** [comment]
I can confirm, latest commit fixed the issues.
