### ISSUE TITLE
VHS_LoadVideoPath: - Custom validation failed for node: video - Invalid file path

### ISSUE THREAD

**Issue by nothingness6** [Kosinkadink/ComfyUI-VideoHelperSuite#227]
![comfyui](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/105210258/8ca2f1e0-abe0-441f-9868-4c8ffcf2b3da)

As you can see in the screenshot, it doesn't allow me to upload any path of video. I also changed the path to D:\Video_Reference.mp4, but no luck.

**Comment by Kosinkadink** [comment]
What's the error that you get in the console?

**Comment by Kosinkadink** [comment]
We will consolidate this issue in this existing one: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/224

Please take a look at my post there, so that we can get more info about the issue.
