### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by vallagurd** [Kosinkadink/ComfyUI-VideoHelperSuite#23]
hi ^^, since yesterday,i can't load vidéo in comfyui:

ERROR:root:Failed to validate prompt for output 48:
ERROR:root:* VHS_LoadVideo 46:
ERROR:root:  - Failed to convert an input value to a INT value: select_every_nth, video, invalid literal for int() with base 10: 'video'
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

thanks

**Comment by Kosinkadink** [comment]
Try to remove and replace that node in your workflow.

**Comment by vallagurd** [comment]
hahaha thanks a lot (i'm a noob),it works!! ^^
