### ISSUE TITLE
Video Batch count

### ISSUE THREAD

**Issue by AhmadZafar176** [Kosinkadink/ComfyUI-VideoHelperSuite#232]
Is there a variable that i can export to know how many times the prompt is going to be executed when using meta_batch for a vid2vid workflow, using meta_batch to avoid OOM error

**Comment by AustinMroz** [comment]
I'm afraid not. I have no way to tell how many frames are in a video until the entire video has been processed.

If you absolutely need it, You can have a second Load Video node which is not included in the Meta Batch, but has select_every_nth equal to the frames_per_batch of the Meta Batch Manager and a super low resolution. Then frame_count of that node will be the number Meta Batch executions.

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/0e48a64c-f487-4ac5-9d12-56c1f80d2363)
