### ISSUE TITLE
Video Combine node NOT saving Animation?

### ISSUE THREAD

**Issue by XTRMsavage** [Kosinkadink/ComfyUI-VideoHelperSuite#235]
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/90519573/35641d1c-3dde-4309-8eb9-e420b1394fbe)
HI I am having this issue, when ever I have more than 1 video combine nodes (Highlighted in red) they wont save the animation, it just saves 1 frame. I have the latest version and updated ComfyUI. Can someone please help. Thanks

**Comment by AustinMroz** [comment]
Looks like it's a simple connection mistake. The ImageCompositeMasked is connected to the upscaled background, not the RepeatImageBatch beneath it. Since there's only one image for the 'destination' input, it's only producing one frame of output.

**Comment by XTRMsavage** [comment]
> Looks like it's a simple connection mistake. The ImageCompositeMasked is connected to the upscaled background, not the RepeatImageBatch beneath it. Since there's only one image for the 'destination' input, it's only producing one frame of output.

Yes, Thank you. :)
