### ISSUE TITLE
Argument 'status'

### ISSUE THREAD

**Issue by davedaverave** [Kosinkadink/ComfyUI-VideoHelperSuite#237]
In the l ast step of my workflow, when exporting video with video combine, i got this...

exception in thread Thread-7: Traceback (most recent call last):   File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner     self.run()   File "/usr/lib/python3.9/threading.py", line 917, in run     self._target(*self._args, **self._kwargs)   File "/notebooks/ComfyUI/main.py", line 113, in prompt_worker     q.task_done(item_id, TypeError: handle_task_done() got an unexpected keyword 

my export is done but then comfy runs into a loop and i need to restart server

**Comment by AustinMroz** [comment]
Can you provide a list of the custom nodes you have installed? It looks like a custom node other than VHS is injecting a fuction over task_done.

**Comment by davedaverave** [comment]
Oh Actually it make sense! they're a lot, but thanks a lot for the help...

0.0 seconds: /notebooks/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-sampler-lcm-alternative
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Universal-Styler
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUi_NNLatentUpscale
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI_Noise
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Eagle-PNGInfo
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.0 seconds: /notebooks/ComfyUI/custom_nodes/comfyui-art-venture
   0.1 seconds (IMPORT FAILED): /notebooks/ComfyUI/custom_nodes/ComfyUI_essentials
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/Comfyui-Superprompt-Unofficial
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.2 seconds: /notebooks/ComfyUI/custom_nodes/rgthree-comfy
   0.2 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.2 seconds (IMPORT FAILED): /notebooks/ComfyUI/custom_nodes/was-node-suite-comfyui
   0.2 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.2 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.4 seconds: /notebooks/ComfyUI/custom_nodes/comfyui_segment_anything
   1.3 seconds: /notebooks/ComfyUI/custom_nodes/comfyui_controlnet_aux
   1.4 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Manager
   1.6 seconds: /notebooks/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

**Comment by AustinMroz** [comment]
Thanks. I did a quick scan over each of the repositories from you list, but wasn't able to find any with a handle_task_done method. It's enough to leave me at a dead end even if I don't particularly trust github's search.

From here, things get a little manual. Depending on what's easier for you, I'd suggest:
- Disabling plugins until you can find which it is, or
- Edit `q.task_done` in main.py back to `q.task_done(item_id, e.outputs_ui)`, add a `breakpoint()` on the line before, run comfyui, then hit `s` to step into the function and see what file handle_task_done is in.

The `status ` arg was added to task_done about 5 months ago, so it's likely a custom node that hasn't been updated in around that long.

**Comment by davedaverave** [comment]
You did already a lot! Thanks 🤩
I'll try to disable plugin one by one, i don't trust me writing code ahah
I'll update here with my findings...
THANKS

**Comment by davedaverave** [comment]
It is comfyui-art-venture, but it's a previous version compatible with py 3.9... thanks again
