### ISSUE TITLE
IndexError: too many indices for tensor of dimension 4

### ISSUE THREAD

**Issue by Li1177** [Kosinkadink/ComfyUI-VideoHelperSuite#238]
The errors that have appeared in the past few days were not present before and everything was running smoothly. Please help me identify where the problem might be.
![29349cc2f74b38388550ded15d66920](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/110624605/a9766fd1-0eee-4198-a9b3-290e53a0267d)
![a47f3573c2dcd4fcf8596bf9eed1ed1](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/110624605/bbd96ee7-9a4e-429f-a390-f8967090b845)

**Comment by AustinMroz** [comment]
Thanks for the report. Looks like an input is somehow being recieved even though there's clearly nothing connected from your image.

I'll add a safety check on the python side to clear the VAE input if images were recieved instead of latents.
