### ISSUE TITLE
Adding an Apple ProRes codec

### ISSUE THREAD

**Issue by roverdude24** [Kosinkadink/ComfyUI-VideoHelperSuite#24]
Request adding an Apple ProRes codec in VideoCombine node:
Profile: ProRes 422 HQ - YCbCr 4:2:2

Thank you in advance.

**Comment by AustinMroz** [comment]
Adding a ProRes.json to video_formats with
```json
{
    "main_pass":
    [
        "-n", "-c:v", "prores_ks",
        "-profile:v","3",
        "-pix_fmt", "yuv422p10"
    ],
     "extension": "mov"
}
```
should do the trick.

**Comment by roverdude24** [comment]
Thank you @AustinMroz
