### ISSUE TITLE
ByPass "Load Video (Path) 🎥🅥🅗🅢" node disable the Queue Prompt Button.

### ISSUE THREAD

**Issue by GoldenCrowInf** [Kosinkadink/ComfyUI-VideoHelperSuite#241]
Hello.
I just updated ComfyUI and the VideoHelper nodes. I reloaded the Load Video nodes. After Update, when I have a Load Video node Bypassed, the Queue Prompt Button just doesn't work. It don't return any error or anything like that. It just doesn't do anything. If I remove the Bypassed node, it works fine. If I turn on the node, it also works fine. It was reported also by someone who was trying to use my Workflow and had the same problem.

This doesn't work:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/121122993/0a238c7f-67d9-4276-a7a3-8ab3ba046c9a)

Also this doesn't work:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/121122993/8edafdda-4b41-4b9f-b65c-aa85e02ec429)

It only run the Workflow if all Load Video nodes are allowed:
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/121122993/d21c09f0-db68-4090-a7cb-f4858cd7a956)

I hope it helps!

**Comment by AustinMroz** [comment]
Thanks
