### ISSUE TITLE
Video Combine Nodes video preview stopped working

### ISSUE THREAD

**Issue by Ginushmal** [Kosinkadink/ComfyUI-VideoHelperSuite#242]
After setting up the above workflow, my Video Combine node stop showing the preview of the output video, it get saved but doesn't preview. this happen with other work-spaces where this node is being used. and i try to uninstall and re install these Nodes too, but it didn't fix this issue, any idea why..????
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/60034915/2fd8ed80-c9ec-4358-b0a2-33d7883bfa04)

**Comment by AustinMroz** [comment]
A fairly major rework to how VHS processes audio was released yesterday. I greatly appreciate the report.

If previews are not displaying even though a playable file has been saved to disk, check the command line. ffmpeg likely ran into an issue when transcoding the preview.

Seperate of that issue, I've fixed the node for converting to the legacy VHS_AUDIO format and added a new node for converting from the legacy VHS_AUDIO format.

**Comment by SamKhoze** [comment]
@AustinMroz I have the same issue

**Comment by manniee07** [comment]
Same issue.

**Comment by Garin2-colab** [comment]
same issue.

**Comment by AustinMroz** [comment]
I've pushed a workaround., let me know if there are any further issues.

@SamKhoze, I would highly advise you update the beforeRegisterNodeDef in audio_preview.js to only apply to your audio_preview node instead as it currently applies to every node.

**Comment by SamKhoze** [comment]
@AustinMroz thank you the preview playback window now is enabled. well noted,
