### ISSUE TITLE
VHS Nodes Previews Overlapping Settings

### ISSUE THREAD

**Issue by makeitrad** [Kosinkadink/ComfyUI-VideoHelperSuite#243]
Thanks for this great custom node! Just wanted to let you know that the previews on OSX Chrome are overlapping the settings. Its workable but something isn't aligning. This happens on the loader and the combine nodes.

Thanks in advance!

**Comment by makeitrad** [comment]
Video Example:

https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/22509743/d08829ed-20d5-4111-9bd6-176da6f117a9

**Comment by AustinMroz** [comment]
I appreciate the report and the video. I haven't been able to reproduce, but agree it's a significant problem.

A couple of follow-up questions:
- Is this a recent issue, or has it been doing this for a while
- Does the amount of overlap you have change with the selected video or resizing the node by dragging a bottom corner?
- If you Right Click -> Hide Preview, does the bottom of the node line up properly with the bottom-most widget?

**Comment by makeitrad** [comment]
Thanks! Seems like this may be a old issue resurfacing. I reported this to Kosinkadink about a year ago an he fixed really quickly. Seems like an identical bug.

**Is this a recent issue, or has it been doing this for a while:**
Started today after updating the node and ComfyUI

**Does the amount of overlap you have change with the selected video or resizing the node by dragging a bottom corner?**
Overlap stays the same when dragging the lower right corner

**If you Right Click -> Hide Preview, does the bottom of the node line up properly with the bottom-most widget?**
Hide preview looks right to me... Image attached for your viewing.
<img width="429" alt="Screenshot 2024-07-06 at 7 18 57 PM" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/22509743/6d88cdf6-f1d6-4f9b-b48b-de5f005ccb9a">

**Comment by makeitrad** [comment]
Think this is a larger issue and not a VHS issue... Can prob close the issue here. Thx!
https://github.com/comfyanonymous/ComfyUI/issues/3965
