### ISSUE TITLE
加载视频时及时预览不可调节Timely preview when loading videos is not adjustable

### ISSUE THREAD

**Issue by zergqyue** [Kosinkadink/ComfyUI-VideoHelperSuite#244]
当我调节帧数上限和跳过x帧时，不能得到正确的及时预览，而是会播放整个视频的预览
When I adjust the frame limit and skip x frames, I cannot get a correct and timely preview, but instead play a preview of the entire video

**Comment by AustinMroz** [comment]
Do you have Advanced Previews enabled?

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/a1b79464-2182-4283-90f0-68cb60c8044c)

**Comment by zergqyue** [comment]
Thank you, the issue has been resolved
