### ISSUE TITLE
VHS load image node, is it possible to clean the history ?

### ISSUE THREAD

**Issue by crasse2** [Kosinkadink/ComfyUI-VideoHelperSuite#245]
Hi !

first thanks a lot for your nodes, they are working great !
I just got a little problem with the load image node that keeps a folder/sequence name history since the beginning, and therefore it is quite long now and barely useful anymore (see screenshot),

then is it possible somewhat to clean or empty this history ?

![vhs_load_image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/20153316/c290140e-987f-433a-8396-4c864324d8f6)

**Comment by AustinMroz** [comment]
On upload, a folder is created in ComfyUI/input. You can remove entries by deleting those folders, but there is not currently a way to do this from the webui.

**Comment by crasse2** [comment]
ooooh so that's where it is kept !! I thought it was related to the browser history and was a bit lost, removing those folder after use is right method ! i'll do that so
thanks a lot for your help !
