### ISSUE TITLE
Which video formats are supported for Load Video node?

### ISSUE THREAD

**Issue by ckao10301** [Kosinkadink/ComfyUI-VideoHelperSuite#255]
mp4, mov, webm, avi, etc?

**Comment by AustinMroz** [comment]
The Load Video nodes are currently set to filter webm, mp4, mkv, and gif, but most all video formats are supported if they are manually selected with Load Video (path).

**Comment by ckao10301** [comment]
Thanks for the info. Since most video formats are supported, would it be possible to add those formats to the filter for Load Video node? (mp4, mov, avi, webm, wmv, flv, avchd, gif, etc) I'm currently using the Load Video node for my api and this would help alot.

**Comment by ckao10301** [comment]
Will use the Load Video (path) node instead
