### ISSUE TITLE
Video Combine 'format' Broken

### ISSUE THREAD

**Issue by dinucci** [Kosinkadink/ComfyUI-VideoHelperSuite#292]
I'm getting the format list in an invalid way.

I tried disable/enable, uninstall, install.

I even reinstalled ComfyUI, new python venv and still get the broken list.

![Screenshot_20240907_092147](https://github.com/user-attachments/assets/19e96ea9-be53-44d2-a0e5-ea7eef39de11)

Failed to validate prompt for output 68:
* (prompt):
  - Exception when validating node: VideoCombine.VALIDATE_INPUTS() missing 1 required positional argument: 'format'
* VHS_VideoCombine 68:
  - Exception when validating node: VideoCombine.VALIDATE_INPUTS() missing 1 required positional argument: 'format'
Output will be ignored

Anyone having the same issue or any idea how to fix it?

**Comment by dinucci** [comment]
got fixed itself after an update!

**Comment by max-sho** [comment]
still facing the same issue
