### ISSUE TITLE
VHS Combine problem 

### ISSUE THREAD

**Issue by NullEqualsZero** [Kosinkadink/ComfyUI-VideoHelperSuite#297]
Well, this is a stupid issue (at least I think). For some reason when I add a "Combine" node, I can't right-click it to set the frame rate as an input (from a widget) which is a must for me.

**Comment by AustinMroz** [comment]
At what point does it stop working? If the context menu isn't showing up when you click on the node, then an extension (likely other than VHS) is throwing an error when it tries to add an option to the context menu.

Open devtools with Ctrl+Shift+i head to the console tab, and check if an error message is created when you right click on the node.

**Comment by NullEqualsZero** [comment]
This is the output 

> Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at getPotentialOutputsAndOutputNodes (:8188/extensions/Com…are-common.js:90:32)
    at node.getExtraMenuOptions (:8188/extensions/Com…i-manager.js:841:35)
    at object.<computed> (:8188/extensions/Com…s/VHS.core.js:14:37)
    at nodeType.getExtraMenuOptions (:8188/extensions/rgt…queue_node.js:49:55)
    at nodeType.getExtraMenuOptions (:8188/assets/index-Drc_oD2f.js:75718:49)
    at __LGraphCanvas.getNodeMenuOptions (:8188/assets/index-Drc_oD2f.js:70866:28)
    at LGraphCanvas.getNodeMenuOptions (:8188/assets/index-BDBCRrlL.js:3558:40)
    at __LGraphCanvas.processContextMenu (:8188/assets/index-Drc_oD2f.js:70943:28)
    at __LGraphCanvas.processMouseDown (:8188/assets/index-Drc_oD2f.js:66038:16)
    at LGraphCanvas.processMouseDown (:8188/assets/index-Drc_oD2f.js:76695:35)
getPotentialOutputsAndOutputNodes @ :8188/extensions/Com…-share-common.js:90
node.getExtraMenuOptions @ :8188/extensions/Com…fyui-manager.js:841
object.<computed> @ :8188/extensions/Com…e/js/VHS.core.js:14
nodeType.getExtraMenuOptions @ :8188/extensions/rgt…nu_queue_node.js:49
nodeType.getExtraMenuOptions @ :8188/assets/index-Drc_oD2f.js:75718
getNodeMenuOptions @ :8188/assets/index-Drc_oD2f.js:70866
LGraphCanvas.getNodeMenuOptions @ :8188/assets/index-BDBCRrlL.js:3558
processContextMenu @ :8188/assets/index-Drc_oD2f.js:70943
processMouseDown @ :8188/assets/index-Drc_oD2f.js:66038
LGraphCanvas.processMouseDown @ :8188/assets/index-Drc_oD2f.js:76695
LGraphCanvas.processMouseDown @ :8188/assets/index-BDBCRrlL.js:5642
LGraphCanvas.processMouseDown @ :8188/extensions/rgt…omfy/rgthree.js:224
LGraphCanvas.processMouseDown @ :8188/assets/index-Drc_oD2f.js:81180

The weird thing is that the same node if imported from a workflow it works fine provided it is probably and older workflow.

**Comment by AustinMroz** [comment]
From the logs, the error is coming from ComfyUI-Manager, but it appears to be a bug I fixed 9 months ago (#93).

Can you double check that ComfyUI-Manager is up to date?

**Comment by NullEqualsZero** [comment]
ok i will check it

**Comment by NullEqualsZero** [comment]
you were right that was it. I thought the update all that the manager had was accounting itself as well but I was wrong. Thanks for the help.
Also, did you find the problem from this line?

>at node.getExtraMenuOptions (:8188/extensions/Com…i-manager.js:841:35)

**Comment by AustinMroz** [comment]
Since there's a lot of callback chaining in js code, the error logs often aren't very helpful beyond the first couple lines. I just happened to remember that the `comfyui-share-common` on the first line was part of ComfyUI-Manager.

**Comment by NullEqualsZero** [comment]
oh gotcha. Thanks again
