### ISSUE TITLE
public web acces after every finished render.

### ISSUE THREAD

**Issue by zejacky** [Kosinkadink/ComfyUI-VideoHelperSuite#310]
Today, I accessed ComfyUI via a local LAN web server. After each completed render, I noticed it would randomly access a specific URL. When I enter this URL in the browser, it displays a video.
Example: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4284322/729b7185-1fca-41d8-bc8d-a770bb2a5ce6

Could you explain what this is?

Thank you

**Comment by AustinMroz** [comment]
Thanks for catching this. That video file is displayed in the node documentation for VHS nodes that use paths as an example of the path suggestion functionality.

A request for this video (or any others that get added) should not be made unless a user opens the documentation for a node. I'll look into a fix for this, but
- The documentation must be parsed as html early to extract the short description used in node previews/tooltips
- Setting a preload of none on the video doesn't seem to prevent the request from being made.
- The larger documentation rewrite I've been working on would not have this issue.
