### ISSUE TITLE
VHS_VideoCombine not found

### ISSUE THREAD

**Issue by RinKirin** [Kosinkadink/ComfyUI-VideoHelperSuite#314]
![image](https://github.com/user-attachments/assets/397c66c2-639a-4c5b-b31d-5ec074a0c35c)

Idk what about that logs but im attach mb it useful
`Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ComfyUI\\ComfyUI\\custom_nodes\\.idea\\__init__.py'

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\.idea module for custom nodes: [Errno 2] No such file or directory: 'E:\\ComfyUI\\ComfyUI\\custom_nodes\\.idea\\__init__.py'
sageattn not found, using sdpa
sageattn not found, using sdpa
sageattn not found, using sdpa`

So im already try what found
`install opencv 4.7.0.72`
`update requirements with opencv-python and imageio-ffmpeg`
`reinstall modules`
`update modules`

Im use Windows 11 23H2 22631.4391

**Comment by MyCroniesSoft** [comment]
Steps to Install Dependencies in the Embedded Python Environment
Activate the Embedded Python Environment: Navigate to the directory where python_embeded is located:

cd c:\Aistudio_pipeline\ComfyUI_windows_portable\python_embeded
Use the Python executable inside this folder to ensure dependencies are installed in the correct environment:

python.exe -m pip install --upgrade pip
Install OpenCV and Other Dependencies: Install the necessary dependencies in the embedded Python environment:

python.exe -m pip install opencv-python opencv-python-headless imageio[ffmpeg]
Verify Installation: After installation, confirm cv2 is properly recognized:

python.exe -c "import cv2; print(cv2.version)"
Restart ComfyUI: Use the provided run_nvidia_gpu.bat to restart ComfyUI:

your drive c:\Aistudio_pipeline\ComfyUI_windows_portable\run_nvidia_gpu.bat
Check Logs for Errors: Monitor the logs to confirm that ComfyUI-VideoHelperSuite loads without errors.

Your welcome, just broke the steps down for you, i rarely pop on to these sites so, so if it helped you let me know if not.... hmmm
