### ISSUE TITLE
[Bug] VHS is affecting scrollbar styles

### ISSUE THREAD

**Issue by LukeG89** [Kosinkadink/ComfyUI-VideoHelperSuite#319]
I don't know why, but I just discovered that VHS is affecting scrollbar styles.
I'm on Chrome, but the same issue is also on Edge.

### Queue sidebar

Normal:
![image](https://github.com/user-attachments/assets/f1d0f322-6490-433c-8b06-146d7c2c75d1)

Altered:
![image](https://github.com/user-attachments/assets/c1c523e7-49a0-4080-afd3-c3dd02372146)

### Text widgets

Normal:
![image](https://github.com/user-attachments/assets/8ae5d661-5f93-4f7c-aea4-8b9f8bc8e46f)

Altered:
![image](https://github.com/user-attachments/assets/529a9254-5f5b-4ae4-b3be-8febbab65a8b)

**Comment by AustinMroz** [comment]
Thanks for the report. I've pushed a fix, but I would appreciate confirmation since both the expected and bugged scrollbars look slightly different on my end.

**Comment by uimne** [comment]
> Thanks for the report. I've pushed a fix, but I would appreciate confirmation since both the expected and bugged scrollbars look slightly different on my end.

After the update, all nodes of VHS failed to load. When I restored to the version on October 31, it's back to normal.

**Comment by LukeG89** [comment]
> Thanks for the report. I've pushed a fix, but I would appreciate confirmation since both the expected and bugged scrollbars look slightly different on my end.

@AustinMroz Confirmed! They are back to normal. I close this issue since this bug is fixed.

![image](https://github.com/user-attachments/assets/643e0b57-7997-4c56-8fbd-beb8d93b7dd7)

----
> After the update, all nodes of VHS failed to load. When I restored to the version on October 31, it's back to normal.

@uimne That's strange, I don't have this problem. Do you have everything up-to-date?

**Comment by AustinMroz** [comment]
@uimne, The commit linked to this issue consists only of minor styling changes in JS code. Since ComfyUI does not check any JS code at startup, the issue you are seeing is the likely the result of other changes which were made and is unrelated to this issue.

My ability to narrow things down is quite limited without any error logs, but most likely, the error you are seeing is the same as #321, which was resolved just ~5 hours before your post.
