### ISSUE TITLE
KSampler errors after updates

### ISSUE THREAD

**Issue by dkamajix** [Kosinkadink/ComfyUI-VideoHelperSuite#32]
Hi,
Im getting these errors when using the ksampler

executing KSampler:

Control type ControlNet may not support required features for sliding context window; use Control objects from Kosinkadink/Advanced-ControlNet nodes.

File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1237, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1207, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 163, in animatediff_sample
return wrap_function_to_inject_xformers_bug_info(orig_comfy_sample)(model, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_utils.py", line 185, in wrapped_function
return function_to_wrap(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 97, in sample
samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 781, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 686, in sample
samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 638, in sample
samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 580, in sample_dpmpp_2m
denoised = model(x, sigmas[i] * s_in, **extra_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 326, in forward
out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 129, in forward
eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 155, in get_eps
return self.inner_model.apply_model(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 314, in apply_model
out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 539, in sliding_sampling_function
cond, uncond = sliding_calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 517, in sliding_calc_cond_uncond_batch
sub_cond = get_resized_cond(cond, full_idxs) if cond is not None else None
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 497, in get_resized_cond
raise ValueError(f"Control type {type(control_item).__name__} may not support required features for sliding context window; use Control objects from K

**Comment by Kosinkadink** [comment]
Make sure to use the Load ControlNet Model (Advanced) node from Advanced-ControlNet instead of the vanilla Load ControlNet Model node. I am considering adding code that will automatically convert non-advance ControlNet objects to advance ones if using my Apply Advanced ControlNet Node, but otherwise I am a bit powerless to easily convert that. Let me know if switching those nodes fixes your issue.

**Comment by dkamajix** [comment]
Ah, yes was about to message I figured it.. but thanks. I am suddenly getting another video load error. going tog post here if you dont mind or I can open another issue.
Prompt outputs failed validation
VHS_LoadVideo:
- Custom validation failed for node: video - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: upload_to_directory - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: desired_frame_rate - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: force_size - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: frame_load_cap - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: skip_first_frames - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
- Custom validation failed for node: select_every_nth - Invalid video file: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\input\LIVINGROOM_GIRL DANCE_432x768.mp4
-

**Comment by dkamajix** [comment]
it was working but suddenly it stopped working..
here is a simple set up still not working
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/c36e08c7-8499-4899-93fa-9a22973a6ca7)

**Comment by Kosinkadink** [comment]
Ah, as part of the fix to the earlier PR, i reverted the input directory to just be "input" again - in your input folder, move the videos out of "VHS_upload" into the outer input folder. The 'VHS_upload' should no longer be part of the path, is this a workflow you just created or one from earlier? And make sure to pull the latest version just in case.

**Comment by dkamajix** [comment]
it seems to be inserting that into the path - Input/VHS_upload/
Like if I drag a video from my drive over..
Im not sure what you mean to remove the video from the vhs_upload cus that does not exist in my drive..

![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/f0b1894b-c50e-4470-8452-eeec33ad7069)

**Comment by Kosinkadink** [comment]
Huh, interesting, can you double check that you have the latest version of the code? I thought I had removed that, but maybe not all the way.

**Comment by dkamajix** [comment]
sure just uninstall and reinstall right?

**Comment by Kosinkadink** [comment]
You can do a manual git pull as well, or selecting "update node" in manager, but yep manual reinstall should work too. I would recommend you also do a git pull after whatever you do regardless so that we get 100% confirmation you are on the latest commit.

**Comment by dkamajix** [comment]
I just did (install reinstall - close and restart) and seems like when i drag an mp4 in there it  inserts input/VHS_upload/ into the front of the path.
How can I remove those cached list in the node as I load them? 
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/5565f954-5912-4db4-a1e8-bc76ffc3aa8b)
if you notice the sumin there are 2 an older and one I just inserted.. the new one has the input/vhs
and should upload to dir be on temp or input

**Comment by Kosinkadink** [comment]
Oooh, the issue is likely in the js code - if you click the button to upload, it should work, but the dragging functionality needs to be altered. See if clicking the button to upload fixes your problem, I'll work on a fix to the dragging thing in a bit

**Comment by dkamajix** [comment]
drag or upload button inserting the pre/ string.
how can I flush the list in there? so there are none?

**Comment by dkamajix** [comment]
interestingly - I tried the other load node with path - gave me this diff error.
maybe a clue?
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/143731847/22f9a5d7-8b63-4dc8-8e3b-0e1a0c02bc4f)

**Comment by dkamajix** [comment]
regular load video from N-Nodes works but I like yours better mate :)

**Comment by Kosinkadink** [comment]
Just pushed some changes that should at the very least make the error more informative, let me know if it fixed your issue/changed your error output!

**Comment by Kosinkadink** [comment]
I just reverted the changes made yesterday, so VHS should be back to stable condition. Let me know if you have any issues now!
