### ISSUE TITLE
SASS selector in JS

### ISSUE THREAD

**Issue by webfiltered** [Kosinkadink/ComfyUI-VideoHelperSuite#323]
It's basically a nit, but it looks like you have some uncompiled SASS in this CSS:

https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/blob/f5469b1caa95c5c5a0f8787ea229d62d3865294b/web/js/VHS.core.js#L169

**Comment by AustinMroz** [comment]
I had never heard of SASS before, but from the looks of it, the syntax for the (now native) nesting selector was inspired by SASS. While it appears to be broadly supported, it is more recently released than I would like, so I'll probably remove its usage anyways.

Thanks for the insight.
