### ISSUE TITLE
Converting CFR to widget doesnt take input?

### ISSUE THREAD

**Issue by 4lt3r3go** [Kosinkadink/ComfyUI-VideoHelperSuite#326]
i'm trying to comand CRF with an external value but seems it doesnt like any values/numers/floath/init or else.
am i doing something wrong?

![image](https://github.com/user-attachments/assets/c7b86fac-c724-45c0-b2b3-6f324c4bc822)

**Comment by AustinMroz** [comment]
I don't believe converted format specific widgets has come up before, but I can confirm that it causes a number of issues I'm looking into. I have a tentative fix for the error being raised on execution, but there's a couple bugs on the frontend affecting what can be connected to crf after you convert it which will take more time.

**Comment by 4lt3r3go** [comment]
really unfortunate since the only trick that can make LTX works is exactly that function right now (also scaling down but not effective as CRF)
https://www.reddit.com/r/StableDiffusion/comments/1h1bb0f/comment/lzakm3q/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by 4lt3r3go** [comment]
Awesome! i'll credit you in my workflow. Thanks
