### ISSUE TITLE
Unable to upload the video due to PIL fallback

### ISSUE THREAD

**Issue by lauretta91** [Kosinkadink/ComfyUI-VideoHelperSuite#34]
I'm struggling to use VHS_LoadVideo - I get the below error whichever video I use.

Failed to load video: input/VHS_upload/xxx.mp4
due to: Unable to open video with pil fallback: input/VHS_upload/xxx.mp4

**Comment by Kosinkadink** [comment]
Hey, a couple days ago main branch was in an unstable state - if you pull the latest changes now, your error should go away!
