### ISSUE TITLE
Exception when validating node: VideoCombine.VALIDATE_INPUTS() missing 1 required positional argument: 'format'

### ISSUE THREAD

**Issue by GeffersAtWork** [Kosinkadink/ComfyUI-VideoHelperSuite#342]
Running on Runpod, the video saver node looks different to how it is in Windows. Tried manually loading in custom-nodes, it seems to give Comfui a problem in that it thinks a restart is required.  Format options look wrong (they give a verbose list of what prores options are).

**Comment by AustinMroz** [comment]
The extra format information is a likely indicator that the frontend js code of VHS isn't running. There might be some finickiness given the uncertainty of the installation, but I would suggest you
- Do a hard refresh (Ctrl+F5) of the web page and check if the format names are still bugged
- Open devtools (Ctrl+Shift+I) and check if the console tab has any error for VHS.core.s
- Verify in the sources tab that extensions > ComfyUI-VideoHelperSuite > VHS.core.js exists

**Comment by GeffersAtWork** [comment]
Thanks, yes, I did the pod all again from scratch and the problem went away. I realised I wasn't properly resetting the pod too, after I had done all that. Cheers for the reply.
