### ISSUE TITLE
Add toggle for meta data

### ISSUE THREAD

**Issue by B34STW4RS** [Kosinkadink/ComfyUI-VideoHelperSuite#37]
Long meta data can cause lock ups in certain video players due to looping reload. 

Add a toggle for choosing how metadata is stored.

**Comment by AustinMroz** [comment]
That is certainly unfortunate to hear and is something I would like to see fixed.

Would you happen to know if the slowdown is specifically related to the metadata being stored as a comment? I originally had metadata storage as a configurable setting in a video format when I was implementing it, but removed the functionality after my testing seemed to show the comment tag as ubiquitous, accessible, and a means to ensure the data existed in a single spot for the loading code.

**Comment by B34STW4RS** [comment]
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/discussions/38

Join us in the discord for better communication man. We'll figure something out.
