### ISSUE TITLE
[feature request] Mask Batch nodes

### ISSUE THREAD

**Issue by nomadoor** [Kosinkadink/ComfyUI-VideoHelperSuite#41]
I think that the workflow of animatediff using inpainting would be more comfortable if there were mask-related nodes like "DuplicateMasks" node and "GetMaskCount" node.

**Comment by Kosinkadink** [comment]
Sure, been thinking for a while about adding it too. Hopefully I'll have time to implement mask versions of the image/latent nodes in the next few days!

**Comment by Kosinkadink** [comment]
Better late than never, they are merged in main now. I have not had the chance to thoroughly test them, so let me know if any of them don't work properly. I will be adding new operations for images/latents soon, so I figured I might as well finally add the mask versions of the nodes.

**Comment by nomadoor** [comment]
Everything is working fine for now.
Thank you for the great work!
