### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by robertvoy** [Kosinkadink/ComfyUI-VideoHelperSuite#47]
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/4003751/e8295621-7eb7-4374-ab49-7d3fd526e678)

There's display issue with the latest update. Using chrome on windows 10.

**Comment by AustinMroz** [comment]
I've found a way to reproduce the error by zooming with the browser and am working on a proper fix, but in the meantime, does resetting the browser zoom with ctrl+0 cause things to line up again?

**Comment by taconugget** [comment]
Doesnt appear to be an issues with zooming on the browser for me. I can change from 100% to 150% and they are always like this. Tested on Chrome and Firefox for MacOS.

**Comment by taconugget** [comment]
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/22509743/51b0072c-11dc-48cd-bde5-eae0c6f85941

Here is a video to show the behavior. Thx for the help!

**Comment by AustinMroz** [comment]
That matches what I was able to reproduce.

I've tested the fix on 3 different browsers and 2 operating systems now, and haven't noticed any issues, so I've pushed it to  main now. Please let me know if it solves the issue.

**Comment by taconugget** [comment]
Works great on my end! Thanks Austin!!
