### ISSUE TITLE
Weird error 

### ISSUE THREAD

**Issue by alexfredo** [Kosinkadink/ComfyUI-VideoHelperSuite#48]
Hi I have a error message with vhs please help ! :
![vvvv](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/24534698/b46d03e7-406e-4ae1-a1c4-0755c815c118)

**Comment by minkdawg** [comment]
me too

**Comment by aleksai** [comment]
kinda same

<img width="875" alt="Screenshot 2023-10-31 at 4 58 50 PM" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/2419256/4219f40e-1c6e-4102-8c75-e60d335f503c">

**Comment by Foolsets** [comment]
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/142786092/429cb072-e9bd-4628-889d-5f0876325644)
same

**Comment by Uniky** [comment]
the same issue here after Updating All, before update, everything works fine
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/24896456/4cf90aea-0db1-4945-84bd-03b7f2ad54bc)

**Comment by AustinMroz** [comment]
Thank you all for the assistance with reporting the error

I've pushed a change that should fix the immediate issue (trying to display a preview for a null video), but please let me know if there's further issues.

**Comment by AustinMroz** [comment]
Hmm... Basic functionality of Load Images (Path) still works for me and that node shouldn't have been affected by any recent changes. It might take some back and forth to find issue.

Could you check if the error occurs when you use a full path for the folder

**Comment by alexfredo** [comment]
Ok thks it's works when I use a full path for the folder !
