### ISSUE TITLE
Feature Request - add prores output

### ISSUE THREAD

**Issue by nickteeple** [Kosinkadink/ComfyUI-VideoHelperSuite#53]
Hello,

Could you please add prores support  as an output format so we can easily take the videos directly into editing software without manually recombining all the frames? Thanks!!!!

https://ottverse.com/ffmpeg-convert-to-apple-prores-422-4444-hq/#FFmpeg_to_Convert_to_Apple_ProRes_4444_Format

**Comment by AustinMroz** [comment]
I wrote a format to support for this a while back in #24

Since it has had multiple requests now, I'll add it officially with the current bundle of pull requests.
