### ISSUE TITLE
Add toggle for video metadata

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#64]
Hey, I got another request to be able to toggle the video metadata saving. Assuming not saving metadata could be an if-statement, we should add something to the Video Combine node to handle that option.

**Comment by AustinMroz** [comment]
Sorry about the delay. I had hoped to roll this functionality into code I was working on that would allow definition of additional widgets inside format json files. This would ensure that the metadata and crf options wouldn't show up when an image format that can't make use of them is selected. However, I ran into unexpected difficulties with these dynamic function arguements not being passed back to the python code which had delayed the implementation.

I'll open a pull request for just toggling metadata soon.
