### ISSUE TITLE
MP4 Codecs not working 

### ISSUE THREAD

**Issue by Inner-Reflections** [Kosinkadink/ComfyUI-VideoHelperSuite#68]
Somthing with the most recent VHS update aba622c97f1a656164658f0d75a801f1ac35a4fe has borked my ability to make h264
no error
just make a garbage unrunable mp4
reverting the the previous commit and everything works fine

**Comment by AustinMroz** [comment]
Thank you for the report. I will likely revert the change and seek out a different solution for #61

**Comment by Kosinkadink** [comment]
@Inner-Reflections I've rolled back the changes, let us know if h264 works for you now!

**Comment by Echolink50** [comment]
Was having the same issue. Can confirm the rollback is working now. I was reinstalling FFMPEG for like an hour and couldn't figure it out. Went to the vhs custom node folder and ran git pull and now it's working

**Comment by Inner-Reflections** [comment]
Everything working fine now!

**Comment by Andrew7127** [comment]
does not work h264/h265

**Comment by Andrew7127** [comment]
height image must  divisible by 2  for working  h264/265
