### ISSUE TITLE
[issue] Error when trying to save MP4 - Error Occured when executing VHS_VideoCombine

### ISSUE THREAD

**Issue by kalkal11** [Kosinkadink/ComfyUI-VideoHelperSuite#74]
Hello,

I've encountered a persistent error when attempting to execute VHS_VideoCombine.  Problem happens specifically when attempting to save MP4, gifs are fine. Despite rolling back commits to as far back as November 4th, the issue remains unchanged. Below is the error output for reference:

```
Error occurred when executing VHS_VideoCombine:

[Errno 32] Broken pipe

File "/home/ubuntu/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/ubuntu/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/ubuntu/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 199, in combine_video
proc.stdin.write(frame.tobytes())
The error suggests a 'Broken pipe', which typically indicates an issue with the communication between different processes or threads. The traceback points to combine_video where the error seems to occur during a write operation to proc.stdin.
```

Any guidance on resolving this error would be appreciated.

Thank you.

**Comment by Kosinkadink** [comment]
We can consolidate this as part of the issue already reported: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/72

Can you try to toggle 'save_metadata' off and see if you still get the error? (you can post your results in the issue I just linked, i'll be closing this one since it's duplicated)
