### ISSUE TITLE
Consider adding gifski supprot for high quality GIFs

### ISSUE THREAD

**Issue by alejobrainz** [Kosinkadink/ComfyUI-VideoHelperSuite#79]
Since GIF is the default file format, maybe you could consider adding gifski support.  It is a library that uses pngquant and the results are very impressive, removing a lot of the dithering associated to gif files.  I've used in prior projects and it's much better than FFMPEG and commercial encoders.  It works through command line, and just likek FFMPEG, for example, `gifski -q 80 -o anim.gif frame*.png`

Here is the project page: https://github.com/ImageOptim/gifski

**Comment by Amorano** [comment]
> Since GIF is the default file format, maybe you could consider adding gifski support

If you are still looking, I added gifski to the Export node in [Jovimetrix](https://github.com/Amorano/Jovimetrix).

Cheers

**Comment by Kosinkadink** [comment]
Nice! I started looking into gifski at the end of January, we should be able to get support for it in VHS sometime this month.

**Comment by Amorano** [comment]
> Nice! I started looking into gifski at the end of January, we should be able to get support for it in VHS sometime this month.

Honestly, just rip my code. Its about 15 lines since its CLI.

**Comment by Amorano** [comment]
> > Since GIF is the default file format, maybe you could consider adding gifski support
> 
> If you are still looking, I added gifski to the Export node in [Jovimetrix](https://github.com/Amorano/Jovimetrix).
> 
> Cheers

Forgot to mention, if you use it, you need to tell it where gifski is.

You will need to add an environment var so it knows you have it installed and where:

set JOV_GIFSKI=<path to gifski>

HTH

**Comment by screan** [comment]
> Nice! I started looking into gifski at the end of January, we should be able to get support for it in VHS sometime this month.

any luck? :)
