### ISSUE TITLE
error when executing image2vid 

### ISSUE THREAD

**Issue by Alexbabylon** [Kosinkadink/ComfyUI-VideoHelperSuite#81]
hi ..anyone have idea what the solution please 
<img width="618" alt="2023-12-01_4-20-26" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/128872360/fd263e58-6e57-4fcc-bf50-00ba840da8ba">

**Comment by Kosinkadink** [comment]
Not a VideoHelperSuite issue, so I'll close the issue. Judging from the error, there was an issue loading the clip_vision model.
