### ISSUE TITLE
Blank output

### ISSUE THREAD

**Issue by Shivakishore14** [Kosinkadink/ComfyUI-VideoHelperSuite#85]
I get the following in the logs

```
/Users/kskshiva/experimentation/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py:93: RuntimeWarning: invalid value encountered in cast
  images = np.clip(images, 0, 255).astype(np.uint8)
```

The output is a blank black gif.

Everything is a fresh install, Using the sample workflow https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved#samples-download-or-drag-images-of-the-workflows-into-comfyui-to-instantly-load-the-corresponding-workflows

Running on Mac M1 Pro (32GB ram)

Image generation works.

**Comment by Kosinkadink** [comment]
Not an issue with VHS, but due to a Mac pytorch bug in M1/M2 Macs. Workaround is mentioned in this thread: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/issues/48
