### ISSUE TITLE
load images   

### ISSUE THREAD

**Issue by bihailantian655** [Kosinkadink/ComfyUI-VideoHelperSuite#88]
After running comfyui    , Add a new image to the folder that has already been uploaded,  this node will not recognize the images in the folder.
![~_4UDITV7Y0SG1$(GSF 4U](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/1be28387-5874-4eca-9207-1151fa95da4a)

![GS5 UJLZF79_5}2URN~}V 1](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/bc475f87-2d5a-4b98-89ff-4313057dc3fb)

root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_images_nodes.py", line 103, in load_images
    return load_images(directory, **kwargs)
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_images_nodes.py", line 44, in load_images
    raise FileNotFoundError(f"No files in directory '{directory}'.")
FileNotFoundError: No files in directory 'H:\ComfyUI\ComfyUI\input\a'.

**Comment by bihailantian655** [comment]
![VQK6)NN%9P$FAVUSDYLJZU8](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/dc450b51-e597-4d68-af84-f42136da58b0)
![Y%HU347%0SPLB2GYDALJQDS](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/36692c79-a09c-4a61-8cbb-1434d7a3ac97)





Even if the folder is empty, you will still be able to read out the pictures,。


hope  to  automatically remove folders from the list                if the  folders  is  deleted

**Comment by AustinMroz** [comment]
I was able to identify and fix a bug that causes the first issue when image_load_cap is 0:
When is_changed_load_images is called with an image_load_cap of 0, it is incorrectly applied and calculates the hash of 0 files. Thus, the hash never changes and the node itself keeps it's cached copy of images.  
However, your images show you experiencing the issue even when image_load_cap is non-zero which I have not been able to reproduce. There's likely still some underlying issue.

**Comment by bihailantian655** [comment]
![$~5(`4M9SL($}DHSKGZ0YNR](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/abad1674-234a-4b81-a052-e6f1d56abd43)
![PLS0SBX}$S8B0}J(2NW8GLS](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/e557fba1-5daa-4c4f-9cc0-c8c9edea8d94)



weird

**Comment by bihailantian655** [comment]
image_load_cap is 0:  means  load all images  in  the  folder?

**Comment by bihailantian655** [comment]
my   fault    ,  I  Placed the image in the wrong directory。
