### ISSUE TITLE
Can we set the framerate higher than 51?

### ISSUE THREAD

**Issue by LuluViBritannia** [Kosinkadink/ComfyUI-VideoHelperSuite#89]
Hi, I'm using Video Combine in multiple workflows. It works great, but it seems to have a framerate cap or something? Starting from 52, the results get extremely slow, ironically. The natural smoothness of a video occurs up to 51, and as soon as I try 52 or more, it's just a broken, slow mess. Even if I have more than 52 images.

I have confirmed it comes from this node. Even in the simplest workflow (a Load Images or Load Video directly plugged into Video Combine), the video gets faster when I raise the framerate up until 51, and loses its smoothness at 52 or higher.

Any solution?

**Comment by AustinMroz** [comment]
I'm not seeing anything specific in the code that would give the results you describe and when running the same simple "Load Video -> Video Combine" workflow, I'm able to get get 120 fps output that seems free of any skips both on my monitor and when played back at reduced speed.

The only (longshot) idea I currently have is that it's related to ffmpeg version.  The code to force usage of the bundled imageio-ffmpeg hasn't made into main yet, so could you check if things are still choppy after changing Line 27 of videohelpersuite/nodes.py from `if ffmpeg_path is None:` to `if True:`?

**Comment by LuluViBritannia** [comment]
Ahhh, never mind, I got it. I was making GIFs, lmao. There may be a limit to a gif framerate in Windows or something. As long as I render an actual video, the framerate does go as high as I want. Thank you!
