### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by Mozoloa** [Kosinkadink/ComfyUI-VideoHelperSuite#9]
I just installed comfy from Stability Matrix (windows), from scratch, then git cloned all the nodes as said in [this CivitAI guide](https://civitai.com/articles/2379), but when I launch comfy, I get this: 

```py
Traceback (most recent call last):
  File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\AI\Image\Stable Diffusion\Data\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 13, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

Any idea ?

**Comment by Kosinkadink** [comment]
You'll need to run ```pip install -r requirements.txt``` while you're in your venv

**Comment by Mozoloa** [comment]
It looks like it worked, but one detail, I needed to cd into `custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite` to install the right requirement.txt

**Comment by youcanyoubing** [comment]
> It looks like it worked, but one detail, I needed to cd into to install the right requirement.txt`custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite`

Please ask the complete command how to run, I do not understand these, try several times are useless

**Comment by Mozoloa** [comment]
> > It looks like it worked, but one detail, I needed to cd into to install the right requirement.txt`custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite`
> 
> Please ask the complete command how to run, I do not understand these, try several times are useless

in the comfy ui folder, click the address bar and replace the path with `powershell.exe` then press enter
then do this : 
```powershell
.\venv\Scripts\activate
Set-Location .\custom_nodes\ComfyUI-VideoHelperSuite\
pip install -r .\requirements.txt
```

**Comment by youcanyoubing** [comment]
> > > It looks like it worked, but one detail, I needed to cd into to install the right requirement.txt`custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite`
> > 
> > 
> > Please ask the complete command how to run, I do not understand these, try several times are useless
> 
> in the comfy ui folder, click the address bar and replace the path with then press enter then do this :`powershell.exe`
> 
> ```powershell
> .\venv\Scripts\activate
> Set-Location .\custom_nodes\ComfyUI-VideoHelperSuite\
> pip install -r .\requirements.txt
> ```

We don't have the same comfyui, so this still doesn't work, it seems like I should just type.\python_embeded\Scripts\activate, or some other directory, so I'll try it
