### ISSUE TITLE
Invalid video file in VHS_LoadVideoPath node

### ISSUE THREAD

**Issue by tuangd** [Kosinkadink/ComfyUI-VideoHelperSuite#90]
I tried to load a vdo into VHS_LoadVideoPath and got the error below.
```
Prompt outputs failed validation
VHS_LoadVideoPath:
- Custom validation failed for node: video - Invalid video file: vdo.mp4
```
Is it the ffmpeg error? But I have ffmpeg install on my machine and it's working fine for other program. hmmm.mmm

**Comment by tuangd** [comment]
Ooops some how it works now...

**Comment by AustinMroz** [comment]
That check is performed well before ffmpeg is called. Usually it just indicates that a file of that name can't be found and is the result of a typo in the path.
