### ISSUE TITLE
Video Combine node doesn't support standard file name string formats

### ISSUE THREAD

**Issue by Jellybit** [Kosinkadink/ComfyUI-VideoHelperSuite#92]
I have a node named (as opposed to titled) ProjectString, which I use in various file saving nodes to sort images into folders named for the thing I'm trying to do. Similarly, I include the checkpoint name into the file name, to keep track of what has what results. Here's my file name string:

%ProjectString.string%/%date:yyyy-M-d%/%CheckpointLoaderSimple.ckpt_name%_%date:hhmmss%

I have formatted this based on ComfyUI's documentation. So let's say I set my Project name to "SciFi", and used the Photon checkpoint. Normally, in all other saving nodes, the name would come out like this:

[Path to output]/SciFi/2023-12-22/Photoreal_photon_v1.safetensors_002926_00001.png

Now, using Video Combine, the output instead looks like this:

[Path to output]/%ProjectString.string%/2023-12-22/%CheckpointLoaderSimple.ckpt_name%_004133_00001.mp4

As you can see, it does get the date and time right, but it fails to pick up on the string references from nodes. It just uses what it's given literally. It would be helpful if it followed the ComfyUI standards.

**Comment by AustinMroz** [comment]
When support for date formatting was added, I didn't see a use for the remaining functionality, and only bothered reimplementing that. It seems the upstream code has since been refactored and can simply be called from our node now. This makes it real easy to satisfy your request and simplify the code on our side.
