### ISSUE TITLE
Video previews in Video Combine nodes disappear upon page reload

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-VideoHelperSuite#97]
Before, Video Combine nodes persisted after a reload, now they disappear. And since the Video Combine nodes don't execute again (as intended), it's difficult to make them reappear again without changing a parameter or image input on the Video Combine nodes.

**Comment by AustinMroz** [comment]
This was changed as a conscientious decision to match the behavior of the save/preview image nodes and to resolve an associated bug: On loading a workflow (either as a json or as an image), it would try to load the output of the prior generation.

I believe this change was also what fixed the discussed issue where the node would always be incorrectly marked as stale in re-execute: The previous output was being submitted as part of the node state and thus always different, but this could be independently fixed if the above is undesirable

**Comment by Kosinkadink** [comment]
Ah, gotcha, thanks for the heads up. That bug that attempted to load the previous output became sorta a nice feature haha. If it would be possible to bring it back in a controlled state that does not cause the node to be marked as stale, that would be great. I think most people saw the previews returning when loading previous workflows or reloading the page as intended behavior.

**Comment by AustinMroz** [comment]
I would also add that, like Preview/Save Image, you can load the most recent execution from history to restore the preview, even after a reload.  I'll look intoit , but would want to take a bit more caution since I'm now aware that ComfyUI-Manager is parsing these values.

**Comment by AustinMroz** [comment]
Upon further review, the required change is close to your original description. It is both easy to restore the functionality now and to undo the change in the future if needed.
